### ISSUE TITLE
Não entendi o seu código. 👍

### ISSUE THREAD

**Issue by CavalcanteC** [ig0r-ferreira/exercicios-python-lets-code-pass#1]
O exercício 4 do módulo 2 está meio estranho 🤔

**Comment by ig0r-ferreira** [comment]
Boa tarde,

Acredito que seu estranhamento seja porque você esperava que eu montasse um dicionário à mão com o total de dias para cada mês e exibisse ele. Provavelmente você diria que Fevereiro contém 28 dias, só que isso não se aplica para anos bissextos.

Dito isso, eu fui um pouco além e utilizei uma função do módulo `calendar` que obtém o total de dias para cada mês usando o ano atual como referência. Assim, para o caso do ano ser bissexto, a função que eu criei retornará um dicionário no qual Fevereiro possui 29 dias.

Por fim, ao retornar a essa solução, percebi que podia simplificá-la um pouco mais e assim o fiz.
Agradeço o questionamento.
